version: '{build}'

skip_tags: true

configuration: Release

platform: x64

branches:
  only:
  - master

install:
- cmd: git submodule update --init

before_build:
- cmd: mkdir build
- cmd: cd build
- cmd: cmake ../ -G "Visual Studio 14 2015 Win64"

build:
  project: PhotoGeo.sln
  parallel: true
  verbosity: minimal
